### ISSUE TITLE
Read matrix from a txt file

### ISSUE THREAD

**Issue by miguel-paco** [echiappe/BonsaiClub#9]
I have these txt files with the transformation matrixes between units. Each line is a row of the matrix and the columns are separated with ','.
[MMc2PXc.txt](https://github.com/miguel-paco/BonsaiClub/files/10852229/MMc2PXc.txt)

In the end the following operation is done to convert units

(xn, yn) = unit n
(xm, ym) = unit m
3x3 Matrix [a,b,c; d,e,f; g,h,i]

xm = (a*xn + b*yn + c) / (g*xn + h*yn + i)
ym = (d*xn + e*yn + f) / (g*xn + h*yn + i)

How would I implement the reading of the matrix to do these operations in bonsai? Or should we just use a python script?

**Comment by bruno-f-cruz** [comment]
Use a CsvReader node with `%f,%f,%f` as a scan pattern.
One way to turn it into a matrix is to just assemble it in an Float[][]. Then use `ExpressionTransforms` or the `Index` operator to access its elements.

[MatrixBuilder.zip](https://github.com/echiappe/BonsaiClub/files/10852524/MatrixBuilder.zip)
